@startuml
skinparam handwritten true

caption Locahost with local container

component "localhost" {
    component "IDE" {

    }

    storage {
        storage sourcecode
    }

component cdk {
    component container {
        component "eap"

        storage {
            storage "war" {

            }
        }
    }
}
}

left to right direction
eap --> war : read
IDE --> eap : connect
IDE --> war : deploy

top to bottom direction
IDE --> sourcecode : rwbuild

@enduml

